// ---- v2 visual enhancement + history mode ----
(function(){
  const oldRenderMoneyFlow=renderMoneyFlow;
  renderMoneyFlow=function(){ oldRenderMoneyFlow(); renderVisualPanels(); };
  function renderVisualPanels(){
    if(!state.race)return;
    const prev=previousSnapshot(3),cur=buildSnapshot(),fm=flowMetrics(),rows=fm.rows,model=fm.model;
    const cfg=[['WIN','win','WIN'],['PLA','pla','P'],['QIN','qin','Q'],['QPL','qpl','QP']];
    $('visualPoolCards').innerHTML=cfg.map(([k,cl,label])=>{const val=cur.pools[k],g=pct(prev?.pools?.[k],val);return `<article class="vpool ${cl}"><div class="vhead"><span>● ${label}</span><span>${g>0?'↗':g<0?'↘':'—'}</span></div><strong>${val>0?'$'+fmtNum(val):'未開售'}</strong><small>3m ${g>=0?'+':''}${g.toFixed(1)}% · 權重 ${((model.weights[k]||0)*100).toFixed(0)}%</small></article>`}).join('');
    const counts={very:0,cold:0,unstable:0,normal:0};rows.forEach(x=>counts[x.type]=(counts[x.type]||0)+1);
    $('insightStats').innerHTML=`<div class="insight-box red"><span>非常異常</span><b>${counts.very}</b></div><div class="insight-box blue"><span>冷馬機會</span><b>${counts.cold}</b></div><div class="insight-box amber"><span>熱門不穩</span><b>${counts.unstable}</b></div><div class="insight-box green"><span>正常</span><b>${counts.normal}</b></div>`;
    const by=Object.fromEntries(activeRunners().map(r=>[runnerNo(r),r]));
    const moves=[...rows].sort((a,b)=>Math.abs(b.flow)-Math.abs(a.flow)).slice(0,5);
    $('topMoves').innerHTML=moves.length?moves.map(x=>{const bars=Math.max(2,Math.min(10,Math.round(Math.abs(x.flow)/10)));return `<div class="move-row"><div class="move-no">${x.no}</div><div class="move-name"><b>${esc(by[x.no]?.name_ch||by[x.no]?.name_en||'')}</b><small>W ${x.winOdds??'—'} · 人氣#${x.rank}</small></div><div class="tiny-bars">${Array.from({length:10},(_,i)=>`<i style="height:${i<bars?7+i*1.5:4}px;opacity:${i<bars?1:.16}"></i>`).join('')}</div><div class="move-tag">${esc(x.tags[0]||'正常')} ${x.flow>=0?'+':''}${x.flow.toFixed(0)}</div></div>`}).join(''):'<div class="empty-mini">等待開售</div>';
    const odds=activeRunners().map(r=>oddsFor('WIN',String(runnerNo(r)))).filter(Boolean);const bins=[0,0,0,0,0,0];odds.forEach(o=>bins[o<3?0:o<5?1:o<10?2:o<20?3:o<50?4:5]++);const mx=Math.max(1,...bins);$('oddsHistogram').innerHTML=bins.map(n=>`<div class="histbar" style="height:${Math.max(5,n/mx*100)}%"><span>${n}</span></div>`).join('');
    const rowByNo=Object.fromEntries(rows.map(x=>[x.no,x]));
    let ordered=activeRunners().map(r=>runnerNo(r)).filter(n=>rowByNo[n]);
    const oddsNum=n=>Number(rowByNo[n]?.winOdds)||999;
    if(state.heatSort==='oddsDesc')ordered.sort((a,b)=>oddsNum(b)-oddsNum(a)); else if(state.heatSort==='qbank')ordered.sort((a,b)=>(rowByNo[b]?.qBankScore||0)-(rowByNo[a]?.qBankScore||0)); else ordered.sort((a,b)=>oddsNum(a)-oddsNum(b));
    if(state.heatColdOnly)ordered=ordered.filter(n=>{const x=rowByNo[n];return x.rank>4&&x.zQ>=.45&&(x.zQP>=.35||x.zP>=.45);});
    const nos=ordered,cols=Math.max(1,nos.length); $('heatmap').style.gridTemplateColumns=`52px repeat(${cols},minmax(52px,1fr))`;
    const isQBank=n=>{const x=rowByNo[n];return !!x&&x.rank>4&&x.qBankScore>=62&&x.zQ>=.45;};
    let h=`<div></div>${nos.map(n=>{const x=rowByNo[n];return `<div class="heat-head ${isQBank(n)?'qbank':''}">#${n}<small>W ${x.winOdds??'—'} · ${x.rank>4?'冷':'熱'}#${x.rank}</small></div>`}).join('')}`;
    for(const k of ['WIN','PLA','QIN','QPL']){h+=`<div class="hlabel">${POOL_LABEL[k]}</div>`;const sh=model.shares[k]||{};const vals=nos.map(n=>sh[n]||0);const max=Math.max(.0001,...vals);h+=nos.map(n=>{const q=(sh[n]||0)/max;const lv=q>.82?5:q>.62?4:q>.42?3:q>.2?2:q>0?1:0;const x=rowByNo[n];const extra=k==='QIN'?` · Qz ${x.zQ>=0?'+':''}${x.zQ.toFixed(1)}σ`:k==='QPL'?` · QPz ${x.zQP>=0?'+':''}${x.zQP.toFixed(1)}σ`:'';return `<div class="heat lv${lv} ${isQBank(n)?'qbank':''}" title="${POOL_LABEL[k]} #${n}${extra}">${Math.round((sh[n]||0)*100)}%</div>`}).join('')}
    $('heatmap').innerHTML=nos.length?h:'<div class="empty-mini" style="grid-column:1/-1">目前冇符合「WIN冷 / Q-QP熱」嘅馬。</div>';
  }
  $('heatmapTools')?.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.hsort){state.heatSort=b.dataset.hsort;document.querySelectorAll('#heatmapTools [data-hsort]').forEach(x=>x.classList.toggle('active',x===b));}if(b.dataset.hfilter==='coldqqp'){state.heatColdOnly=!state.heatColdOnly;b.classList.toggle('active',state.heatColdOnly);}renderVisualPanels();});
  let historyRaceNo=1;
  function buildRaceChips(){ $('historyRaceChips').innerHTML=Array.from({length:12},(_,i)=>`<button class="${i+1===historyRaceNo?'active':''}" data-hrace="${i+1}">R${i+1}</button>`).join(''); }
  function histKey(date,venue,race){return `smartbet-flow3:${date}:${venue}:${race}`}
  function pickBacktestSnapshot(snaps){if(!snaps.length)return null;const withMins=snaps.filter(x=>Number.isFinite(Number(x.minutesToPost))&&Number(x.minutesToPost)>=0);if(withMins.length){return withMins.slice().sort((a,b)=>Math.abs(Number(a.minutesToPost)-3)-Math.abs(Number(b.minutesToPost)-3))[0];}return snaps[snaps.length-1];}
  function renderOutcomeStats(rows){const top3=(rows||[]).filter(x=>Number(x.finish)<=3);const win=top3.find(x=>Number(x.finish)===1);const longshots=top3.filter(x=>Number(x.winOdds)>=10);const maxLong=top3.slice().sort((a,b)=>Number(b.winOdds||0)-Number(a.winOdds||0))[0];const avg=top3.length?top3.reduce((a,x)=>a+(Number(x.winOdds)||0),0)/top3.length:0;$('historyOutcomeStats').innerHTML=`<div class="history-note"><span>頭馬賠率</span><b>${win?.winOdds||'—'}</b></div><div class="history-note"><span>頭三冷門數 ≥10倍</span><b>${longshots.length}</b></div><div class="history-note"><span>最大冷門入位</span><b>${maxLong?.winOdds?`${maxLong.winOdds}倍 · #${maxLong.horseNo}`:'—'}</b></div><div class="history-note"><span>頭三平均賠率</span><b>${avg?avg.toFixed(1):'—'}</b></div>`;}
  function renderArchive(data){
    let snaps=[];try{snaps=JSON.parse(localStorage.getItem(histKey(data.date,data.venueCode,data.raceNo))||'[]')}catch{}
    const pos=Object.fromEntries((data.results||[]).map(x=>[Number(x.horseNo),Number(x.finish)]));
    if(!snaps.length){$('historyArchiveStatus').innerHTML='呢場 <strong>冇本機 Money Flow 快照</strong>。你仍然可以用官方賽果／最終賠率做結果對照；由而家開始睇嘅場次會自動累積快照。';$('historyBacktestStats').innerHTML='<div class="bt-stat"><span>可回測快照</span><b>0</b></div><div class="bt-stat"><span>3分鐘訊號</span><b>未保存</b></div>';$('historyBacktest').innerHTML='';return;}
    const snap=pickBacktestSnapshot(snaps),exp=snap?.expected||{},cross=snap?.cross||{},sh=snap?.shares||{};const ranked=Object.keys(exp).map(Number).filter(n=>exp[n]>0).sort((a,b)=>exp[b]-exp[a]);const rank=Object.fromEntries(ranked.map((n,i)=>[n,i+1]));const exQ={},exQP={},exP={};ranked.forEach(n=>{exQ[n]=logExcess(sh.QIN?.[n]||0,exp[n]||0);exQP[n]=logExcess(sh.QPL?.[n]||0,exp[n]||0);exP[n]=logExcess(sh.PLA?.[n]||0,exp[n]||0)});const zQ=robustZMap(exQ),zQP=robustZMap(exQP),zP=robustZMap(exP);
    const edges=ranked.filter(n=>(rank[n]||99)>4).map(n=>{const cold=clamp(((rank[n]||99)-4)/6,0,1),qscore=Math.round(sigmoidScore(.48*(zQ[n]||0)+.27*(zQP[n]||0)+.13*(zP[n]||0)+.16*cold-.08));return {n,rank:rank[n],ratio:cross[n]>0?cross[n]/exp[n]-1:0,qscore,zq:zQ[n]||0,finish:pos[n]||null};}).sort((a,b)=>b.qscore-a.qscore||b.zq-a.zq).slice(0,5);
    const top3Edges=edges.slice(0,3),hits=top3Edges.filter(x=>x.finish&&x.finish<=2),top1Hit=top3Edges[0]?.finish&&top3Edges[0].finish<=2,finished=top3Edges.filter(x=>x.finish),avgFinish=finished.length?finished.reduce((a,x)=>a+x.finish,0)/finished.length:null,mins=Number(snap?.minutesToPost);
    $('historyArchiveStatus').innerHTML=`已搵到 <strong>${snaps.length} 個 Money Flow 快照</strong>；回測優先採用${Number.isFinite(mins)?`開跑前約 ${Math.max(0,mins).toFixed(1)} 分鐘`:'最接近臨場'}嘅 snapshot。`;
    $('historyBacktestStats').innerHTML=`<div class="bt-stat"><span>TOP3 前二命中</span><b>${hits.length}/3</b></div><div class="bt-stat"><span>TOP1 Q膽入前二</span><b>${top1Hit?'YES':'NO'}</b></div><div class="bt-stat"><span>平均最終名次</span><b>${avgFinish?avgFinish.toFixed(1):'—'}</b></div><div class="bt-stat"><span>快照數</span><b>${snaps.length}</b></div>`;
    $('historyBacktest').innerHTML=edges.map((x,i)=>`<div class="bt-row"><b>${i+1}</b><div>#${x.n} · WIN人氣#${x.rank}<br><small>Q膽 ${x.qscore} · Q ${x.zq>=0?'+':''}${x.zq.toFixed(1)}σ</small></div><div class="${x.finish&&x.finish<=2?'bt-hit':'bt-miss'}">${x.finish?`第${x.finish}名`:'—'}</div><div>${x.finish&&x.finish<=2?'✓ 命中前二':'對照'}</div></div>`).join('')||'<div class="empty-mini">快照不足以重建Q膽排序。</div>';
  }
  function collectBacktestSnapshots(){const out=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key?.startsWith('smartbet-flow3:'))continue;let arr=[];try{arr=JSON.parse(localStorage.getItem(key)||'[]')}catch{}const [,date,venue,race]=key.split(':');out.push({key,date,venue,race:Number(race),snapshots:arr});}return out;}
  function downloadText(name,text,type='application/json'){const blob=new Blob([text],{type});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
  function exportJson(){const data=collectBacktestSnapshots();downloadText(`smartbet-backtest-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({version:2,exportedAt:new Date().toISOString(),data},null,2));}
  function exportCsv(){const lines=['date,venue,race,timestamp,minutesToPost,horseNo,expectedShare,crossShare,excessPct,winOdds'];for(const g of collectBacktestSnapshots())for(const snap of g.snapshots||[]){const nos=new Set([...Object.keys(snap.expected||{}),...Object.keys(snap.cross||{})]);for(const n of nos){const e=Number(snap.expected?.[n]||0),c=Number(snap.cross?.[n]||0),x=e>0?(c/e-1)*100:0,w=Number(snap.odds?.WIN?.[n]||0)||'';lines.push([g.date,g.venue,g.race,new Date(snap.t).toISOString(),Number.isFinite(Number(snap.minutesToPost))?Number(snap.minutesToPost).toFixed(2):'',n,e.toFixed(6),c.toFixed(6),x.toFixed(2),w].join(','));}}downloadText(`smartbet-backtest-${new Date().toISOString().slice(0,10)}.csv`,lines.join('\n'),'text/csv;charset=utf-8');}
  async function loadHistory(){const date=$('historyDate').value,venue=$('historyVenue').value;$('historyStatus').textContent='讀取中';$('historyResults').innerHTML='<div class="empty">正在讀取 HKJC 官方賽果…</div>';try{const u=`/api/history?date=${encodeURIComponent(date)}&venueCode=${venue}&raceNo=${historyRaceNo}`;const r=await fetch(u,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||`HTTP ${r.status}`);$('historyStatus').textContent='官方資料 OK';$('historySummary').textContent=`${j.date} · ${j.venueCode==='ST'?'沙田':'跑馬地'} · 第 ${j.raceNo} 場`;const rows=j.results||[];renderOutcomeStats(rows);$('historyResults').innerHTML=rows.map(x=>`<div class="result-horse ${Number(x.finish)<=3&&Number(x.winOdds)>=10?'longshot-hit':''}"><div class="finish">${x.finish}</div><div class="hno">${x.horseNo}</div><div><b>${esc(x.horse)}</b><small style="display:block">${esc(x.jockey)} · ${esc(x.trainer)}</small>${Number(x.finish)<=3&&Number(x.winOdds)>=10?'<span class="longshot-chip">冷門入位</span>':''}</div><div><small>WIN</small><b style="display:block">${esc(x.winOdds||'—')}</b></div><div class="finish-time"><small>時間</small><b style="display:block">${esc(x.finishTime||'—')}</b></div></div>`).join('');$('historyDividends').innerHTML=(j.dividends||[]).slice(0,16).map(x=>`<div class="div-chip"><span>${esc(x.pool)}</span><b>${esc(x.combination||'—')}</b><small>${esc(x.dividend||'')}</small></div>`).join('')||'<div class="empty-mini">暫未解析到派彩表</div>';renderArchive(j);}catch(e){$('historyStatus').textContent='讀取失敗';$('historySummary').textContent='呢個場次暫時讀唔到';$('historyResults').innerHTML=`<div class="empty">${esc(e.message)}</div>`;$('historyDividends').innerHTML='';$('historyOutcomeStats').innerHTML='<div class="history-note"><span>回測</span><b>暫無資料</b></div>';$('historyBacktestStats').innerHTML='';$('historyBacktest').innerHTML='';}}
  buildRaceChips(); $('exportBacktestJson').onclick=exportJson;$('exportBacktestCsv').onclick=exportCsv;
  $('historyRaceChips').addEventListener('click',e=>{const b=e.target.closest('[data-hrace]');if(!b)return;historyRaceNo=Number(b.dataset.hrace);buildRaceChips();loadHistory();});$('historyLoad').onclick=loadHistory;
  $('modeSwitch').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(!b)return;document.querySelectorAll('#modeSwitch button').forEach(x=>x.classList.toggle('active',x===b));const hist=b.dataset.mode==='history';$('liveDashboard').classList.toggle('hidden-mode',hist);$('historyDashboard').classList.toggle('active',hist);document.querySelector('.bottom-bar').style.display=hist?'none':'';if(hist)loadHistory();});
})();
