(function(){
'use strict';
if(window.__SMARTBET_BACKTEST_V5__)return;window.__SMARTBET_BACKTEST_V5__='20260915-bt2';
var d=document,API='https://ajnunehxtiofcphdyhqn.supabase.co/functions/v1/smartbet-backtest-v2',S={data:null,strategy:'smartflow'};
function q(id){return d.getElementById(id)}function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function style(){var css='.btcard{border-color:#3b594a!important}.btTabs{display:flex;gap:5px;overflow:auto;margin:8px 0}.btTabs button{border:1px solid #315442;background:#081b13;color:#9bb7a7;border-radius:99px;padding:7px 10px;font-size:8px;font-weight:900;white-space:nowrap}.btTabs button.on{background:#72ebb0;color:#052015}.bttable{overflow:auto}.btrow{display:grid;grid-template-columns:54px 58px 72px 72px 72px 68px 68px 82px;gap:4px;min-width:570px;align-items:center}.btrow span{padding:6px 4px;border-bottom:1px solid #173327;text-align:center;font-size:8px}.btrow.head span{color:#789686;font-weight:900}.btgood{color:#72ebb0}.btbad{color:#ff98a5}.btwarn{color:#ffd36a}.btcompare{display:grid;grid-template-columns:repeat(5,1fr);gap:5px;margin-top:8px}.btcmp{background:#071710;border:1px solid #284737;border-radius:10px;padding:8px;text-align:center}.btcmp small{display:block;color:#789686;font-size:7px}.btcmp b{font-size:12px}.btzero{padding:12px;border:1px dashed #315442;border-radius:10px;color:#789686;text-align:center;font-size:9px}@media(max-width:700px){.btcompare{grid-template-columns:1fr 1fr}}';var s=d.createElement('style');s.textContent=css;d.head.appendChild(s)}
function ensure(){var replay=q('replay');if(!replay)return false;if(!q('backtestV2')){var x=d.createElement('div');x.id='backtestV2';x.className='card btcard';x.innerHTML='<div class=sectionhead><div><div class=ey>BACKTEST LAB v2</div><div class=title>歷史回測 · No-Look-Ahead</div><div id=btSub class=sub>讀取歷史樣本…</div></div><button id=btRefresh class=tinybtn>重新整理</button></div><div id=btTabs class=btTabs><button data-s=smartflow class=on>SmartFlow Top3</button><button data-s=cold>Cold Surge</button><button data-s=band>Same-Odds Band</button><button data-s=favorite>Favorite Baseline</button></div><div id=btTable class=bttable></div><div class=ey style="margin-top:10px">SMARTFLOW vs FAVORITE BASELINE</div><div id=btCompare class=btcompare></div><div id=btNotes class=rcnote></div>';replay.insertBefore(x,replay.firstChild);q('btTabs').onclick=function(e){var t=e.target;if(!t.getAttribute('data-s'))return;S.strategy=t.getAttribute('data-s');var bs=q('btTabs').getElementsByTagName('button');for(var i=0;i<bs.length;i++)bs[i].classList.toggle('on',bs[i]===t);render()};q('btRefresh').onclick=function(){load(true)}}return true}
function pct(v){return v==null?'NO SAMPLE':v.toFixed?v.toFixed(1)+'%':v+'%'}function roi(v){if(v==null)return 'NO SAMPLE';return (v>=0?'+':'')+v.toFixed(1)+'%'}function cls(v){return v==null?'':v>0?'btgood':v<0?'btbad':'btwarn'}
function render(){var x=S.data;if(!x)return;var stages=['T-17','T-10','T-5','T-3','T-1'],h='<div class="btrow head"><span>Stage</span><span>Races</span><span>Winner</span><span>Pick Top3</span><span>Coverage</span><span>WIN ROI</span><span>Max DD</span><span>95% CI</span></div>';for(var i=0;i<stages.length;i++){var st=stages[i],m=x.stages&&x.stages[st]&&x.stages[st][S.strategy]?x.stages[st][S.strategy]:null;if(!m)continue;h+='<div class=btrow><span><b>'+st+'</b></span><span>'+m.racesWithPicks+'/'+m.races+'</span><span>'+pct(m.winnerHitRate)+'</span><span>'+pct(m.pickTop3Rate)+'</span><span>'+pct(m.top3Coverage)+'</span><span class="'+cls(m.winROI)+'">'+roi(m.winROI)+'</span><span>'+m.maxDrawdown+'</span><span>'+(m.ci95?m.ci95[0]+'–'+m.ci95[1]+'%':'—')+'</span></div>'}q('btTable').innerHTML=x.raceGroups?h:'<div class=btzero>目前未有已完成賽事樣本。等 snapshot + 官方結果開始累積後，呢度會自動出真實回測數據。</div>';q('btSub').textContent=x.raceGroups+' race groups · '+x.snapshotCount+' snapshots · '+x.resultCount+' results';var c='';for(i=0;i<stages.length;i++){st=stages[i];var a=x.stages[st].smartflow,b=x.stages[st].favorite,delta=(a.atLeastOneTop3Rate!=null&&b.atLeastOneTop3Rate!=null)?Number((a.atLeastOneTop3Rate-b.atLeastOneTop3Rate).toFixed(1)):null;c+='<div class=btcmp><small>'+st+'</small><b class="'+cls(delta)+'">'+(delta==null?'—':(delta>=0?'+':'')+delta+'pp')+'</b><small>至少1匹入Top3<br>vs Favorite</small></div>'}q('btCompare').innerHTML=c;q('btNotes').textContent=(x.notes||[]).join(' · ')}
function load(force){if(!ensure())return;q('btSub').textContent='讀取歷史樣本…';fetch(API+(force?'?t='+Date.now():''),{cache:'no-store'}).then(function(r){return r.text().then(function(t){var j=JSON.parse(t);if(!r.ok||j.ok===false)throw new Error(j.error||r.status);return j})}).then(function(j){S.data=j;render()}).catch(function(e){q('btSub').textContent='Backtest 暫時未能更新 · '+String(e&&e.message||e)})}
function boot(){if(!ensure()){setTimeout(boot,350);return}load(false)}style();boot();
})();