(function(){
'use strict';
if(window.__SMARTBET_CONTROL_V3__)return;window.__SMARTBET_CONTROL_V3__='20260915-rc1';
var doc=document,API='https://ajnunehxtiofcphdyhqn.supabase.co/functions/v1/smartbet-race-control',state={ctx:'',data:null,horse:null,timer:null};
function q(id){return doc.getElementById(id)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function addStyle(){var css='.rcard{border-color:#2e5943!important;background:linear-gradient(135deg,#0a2118,#07140f)!important}.rchead{display:flex;justify-content:space-between;align-items:flex-start;gap:8px}.rcphase{font-size:9px;font-weight:950;padding:6px 9px;border-radius:99px;background:#143524;color:#86efb7;white-space:nowrap}.rcgrid{display:grid;grid-template-columns:repeat(5,1fr);gap:5px;margin-top:9px}.rcstat{background:#071710;border:1px solid #244535;border-radius:10px;padding:7px;text-align:center}.rcstat small{display:block;font-size:7px;color:#789686;margin-bottom:4px}.rcstat b{font-size:10px}.ok{color:#72ebb0}.miss{color:#ff8996}.future{color:#789686}.warn2{color:#ffd36a}.stageStrip{display:flex;gap:5px;overflow:auto;padding:8px 0 1px}.stageChip{min-width:58px;border:1px solid #244535;border-radius:10px;background:#071710;padding:7px;text-align:center}.stageChip b{display:block;font-size:10px}.stageChip small{font-size:7px;color:#789686}.stageChip.okc{border-color:#2d7652}.stageChip.missc{border-color:#7a333b;background:#231116}.stageChip.futurec{opacity:.62}.lifebox{border-color:#315943!important}.horsePick{display:flex;gap:5px;overflow:auto;padding:6px 0}.horsePick button{min-width:34px;border:1px solid #315442;background:#081b13;color:#9bb7a7;border-radius:9px;padding:7px;font-weight:950}.horsePick button.on{background:#72ebb0;color:#052015}.lifeSummary{font-size:11px;font-weight:900;margin:5px 0 8px}.lifeCells{display:flex;gap:5px;overflow:auto;padding-bottom:4px}.lifeCell{min-width:68px;border:1px solid #244535;border-radius:10px;background:#071710;padding:8px;text-align:center}.lifeCell.post{border-color:#67402a}.lifeCell b{display:block;font-size:15px;margin:3px 0}.lifeCell small{font-size:7px;color:#789686}.lifeCell.missing{border-color:#73313a;background:#221116}.lifeArrow{color:#456a56;font-size:14px;align-self:center}.rcnote{font-size:8px;color:#789686;margin-top:7px}@media(max-width:700px){.rcgrid{grid-template-columns:repeat(2,1fr)}.rcgrid .rcstat:last-child{grid-column:1/-1}}';var s=doc.createElement('style');s.textContent=css;doc.head.appendChild(s)}
function parseCtx(){var t=q('homeMeeting'),s=t?t.textContent:'';var m=String(s).match(/\b(HV|ST)\s+(\d{4}-\d{2}-\d{2})\s*·\s*R(\d+)/);if(m)return {venue:m[1],date:m[2],race:Number(m[3])};var b=q('meeting'),x=b?b.textContent:'';m=String(x).match(/\b(HV|ST)\s+(\d{4}-\d{2}-\d{2})\s*·\s*R(\d+)/);return m?{venue:m[1],date:m[2],race:Number(m[3])}:null}
function key(c){return c?c.date+'|'+c.venue+'|'+c.race:''}
function labelCollector(v){return v==='OK'?'正常':v==='LATE'?'延遲':v==='DONE'?'完成':'待命'}
function clsCollector(v){return v==='OK'||v==='DONE'?'ok':v==='LATE'?'miss':'future'}
function statusStage(s){return s==='OK'?['✓','okc','ok']:s==='MISSING'?['!','missc','miss']:['·','futurec','future']}
function aiState(d,which){var a=which==='t3'?d.ai.t3:d.ai.t1,stage=which==='t3'?'T-3':'T-1',cov=d.coverage[stage];if(a)return ['已鎖定','ok'];if(cov==='FUTURE')return ['等待','future'];return ['未鎖定','miss']}
function lateState(d){if(d.lateReady)return ['可分析','ok'];if((d.coverage['T+1']||'FUTURE')==='FUTURE')return ['等待 T0','future'];return ['未就緒','miss']}
function fmtAge(v){return v==null?'—':v<1?'<1m':v.toFixed?v.toFixed(1)+'m':v+'m'}
function ensure(){var home=q('home'),bars=q('bars');if(!home||!bars)return false;if(!q('raceControl')){var rc=doc.createElement('div');rc.id='raceControl';rc.className='card rcard';rc.innerHTML='<div class=rchead><div><div class=ey>RACE DAY CONTROL ROOM</div><div class=title>賽日控制台</div><div id=rcSub class=sub>檢查資料鏈路…</div></div><span id=rcPhase class=rcphase>--</span></div><div id=rcStats class=rcgrid></div><div id=rcStages class=stageStrip></div><div class=rcnote>只顯示真實已收 snapshots；缺失時間點不補造。0+ 資料只作即時／事後分析，不回寫 T-3/T-1 AI Lock。</div>';home.insertBefore(rc,home.children[1]||home.firstChild)}if(!q('lifePanel')){var lp=doc.createElement('div');lp.id='lifePanel';lp.className='card lifebox';lp.innerHTML='<div class=rchead><div><div class=ey>SMARTFLOW LIFECYCLE</div><div class=title>資金生命線 · T-17 → T+5</div><div id=lifeSub class=sub>等待 snapshots</div></div><span id=lifePhase class=rcphase>--</span></div><div id=lifeHorses class=horsePick></div><div id=lifeSummary class=lifeSummary>尚未有可分析資料</div><div id=lifeCells class=lifeCells></div><div class=rcnote>SmartFlow 是跨池異常強度，不是勝率。T+ 資料代表延後資金更新／延續流入，不代表開跑後仍可投注。</div>';bars.insertBefore(lp,bars.firstChild)}return true}
function renderControl(d){var a3=aiState(d,'t3'),a1=aiState(d,'t1'),lt=lateState(d);q('rcPhase').textContent=d.phase||'--';q('rcSub').textContent=d.venueCode+' '+d.date+' · R'+d.raceNo+' · snapshots '+d.snapshotCount+(d.latestAgeMin!=null?' · 最新 '+fmtAge(d.latestAgeMin):'');q('rcStats').innerHTML='<div class=rcstat><small>COLLECTOR</small><b class="'+clsCollector(d.collector)+'">'+labelCollector(d.collector)+'</b></div><div class=rcstat><small>SNAPSHOTS</small><b class="'+(d.snapshotCount?'ok':'future')+'">'+d.snapshotCount+'</b></div><div class=rcstat><small>T-3 AI</small><b class="'+a3[1]+'">'+a3[0]+'</b></div><div class=rcstat><small>T-1 AI</small><b class="'+a1[1]+'">'+a1[0]+'</b></div><div class=rcstat><small>0+ LATE FLOW</small><b class="'+lt[1]+'">'+lt[0]+'</b></div>';var h='';for(var i=0;i<d.stages.length;i++){var p=d.stages[i],s=statusStage(p.state);h+='<div class="stageChip '+s[1]+'"><small>'+esc(p.key)+'</small><b class="'+s[2]+'">'+s[0]+'</b><small>'+(p.minutesToPost==null?p.state:(p.minutesToPost>0?'T-':'T+')+Math.abs(p.minutesToPost).toFixed(1))+'</small></div>'}q('rcStages').innerHTML=h}
function pickDefault(d){if(state.horse&&d.horses.indexOf(state.horse)>=0)return state.horse;var best=null,score=-1;for(var i=0;i<d.horses.length;i++){var n=String(d.horses[i]),v=null;for(var j=d.stages.length-1;j>=0;j--){if(d.stages[j].idx&&typeof d.stages[j].idx[n]!=='undefined'){v=Math.abs(Number(d.stages[j].idx[n]));break}}if(v!=null&&v>score){score=v;best=d.horses[i]}}return best||d.horses[0]||null}
function lifeLabel(vals){if(!vals.length)return '等待 snapshots';var map={};for(var i=0;i<vals.length;i++)map[vals[i].k]=vals[i].v;var t0=map['T0'],last=vals[vals.length-1].v;if(t0!=null&&vals[vals.length-1].k.indexOf('T+')===0){var dd=last-t0;if(dd>=12)return '🔴 0+ STILL FLOWING · T0後仍然增強 '+(dd>=0?'+':'')+dd;if(dd<=-12)return '⚪ 0+ FADE · T0後轉弱 '+dd}if(map['T-3']!=null&&map['T0']!=null&&map['T0']-map['T-3']>=18)return '⚡ 最後加速 · T-3 → T0';if(map['T-17']!=null&&map['T-5']!=null&&map['T-5']-map['T-17']>=18)return '↗ 早段建立 · T-17 → T-5';return '持續觀察 · 以跨池強度變化為主'}
function renderLife(d){state.horse=pickDefault(d);q('lifePhase').textContent=d.phase||'--';q('lifeSub').textContent=d.venueCode+' '+d.date+' · R'+d.raceNo+' · '+(state.horse?'#'+state.horse:'尚未有馬匹資料');var hh='';for(var i=0;i<d.horses.length;i++){var n=d.horses[i];hh+='<button data-horse="'+n+'" class="'+(n===state.horse?'on':'')+'">#'+n+'</button>'}q('lifeHorses').innerHTML=hh;if(!state.horse){q('lifeSummary').textContent='尚未有可分析資料';q('lifeCells').innerHTML='<div class=sub>Collector 會由 T-45 開始保存 snapshot。</div>';return}var vals=[],html='',sn=String(state.horse);for(i=0;i<d.stages.length;i++){var p=d.stages[i],has=p.idx&&typeof p.idx[sn]!=='undefined',v=has?Number(p.idx[sn]):null;if(has)vals.push({k:p.key,v:v});var post=p.key.indexOf('T+')===0,cl=v==null?'missing':v>=0?'':'',vc=v==null?'miss':v>=0?'ok':'miss';html+='<div class="lifeCell '+(post?'post ':'')+cl+'"><small>'+esc(p.key)+'</small><b class="'+vc+'">'+(v==null?'—':(v>=0?'+':'')+v)+'</b><small>'+(p.state==='MISSING'?'MISSING':p.state==='FUTURE'?'等待':p.minutesToPost==null?'已收':Math.abs(p.minutesToPost).toFixed(1)+'m')+'</small></div>'}q('lifeSummary').textContent=lifeLabel(vals);q('lifeCells').innerHTML=html}
function render(d){state.data=d;renderControl(d);renderLife(d)}
function load(force){if(!ensure())return;var c=parseCtx();if(!c)return;var k=key(c);if(force||k!==state.ctx){state.ctx=k;state.horse=null}var u=API+'?date='+encodeURIComponent(c.date)+'&venueCode='+encodeURIComponent(c.venue)+'&raceNo='+c.race;fetch(u,{cache:'no-store'}).then(function(r){return r.text().then(function(t){var j=JSON.parse(t);if(!r.ok||j.ok===false)throw new Error(j.error||r.status);return j})}).then(render).catch(function(e){if(q('rcSub'))q('rcSub').textContent='Control Room 暫時未能更新 · '+String(e&&e.message||e)})}
function boot(){if(!ensure()){setTimeout(boot,300);return}q('lifeHorses').onclick=function(e){var t=e.target;while(t&&t!==this&&!t.getAttribute('data-horse'))t=t.parentNode;if(t&&t!==this&&state.data){state.horse=Number(t.getAttribute('data-horse'));renderLife(state.data)}};load(true);state.timer=setInterval(function(){var c=parseCtx(),k=key(c);load(k!==state.ctx)},30000);var hm=q('homeMeeting');if(hm&&window.MutationObserver)new MutationObserver(function(){setTimeout(function(){load(true)},150)}).observe(hm,{childList:true,characterData:true,subtree:true})}
addStyle();boot();
})();