(()=>{'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=x=>Number.isFinite(Number(x))?Number(x):0,fmt=x=>Number.isFinite(Number(x))?Number(x).toLocaleString('en-HK',{maximumFractionDigits:1}):'—',money=x=>Number.isFinite(Number(x))?Math.round(Number(x)).toLocaleString('en-HK'):'—',pct=x=>Number.isFinite(Number(x))?(100*Number(x)).toFixed(1)+'%':'—',today=()=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Hong_Kong',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`},time=t=>new Date(t).toLocaleTimeString('zh-HK',{timeZone:'Asia/Hong_Kong',hour:'2-digit',minute:'2-digit',hour12:false}),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const params=new URLSearchParams(location.search);$('#date').value=/^20\d{2}-\d{2}-\d{2}$/.test(params.get('date')||'')?params.get('date'):today();$('#venue').value=['HV','ST'].includes(params.get('venue'))?params.get('venue'):'HV';for(let i=1;i<=12;i++)$('#race').add(new Option('第 '+i+' 場',String(i)));$('#race').value=/^\d+$/.test(params.get('race')||'')?String(clamp(+params.get('race'),1,12)):'8';
let frames=[],at=0,racing=null,official=null,reqId=0,sort='signal',model='balance';const types=['WIN','PLA','QIN','QPL'],poolNames={WIN:'獨贏',PLA:'位置',QIN:'連贏',QPL:'位置Q'};const ctx=()=>({date:$('#date').value,venueCode:$('#venue').value,raceNo:+$('#race').value});const url=(path,c)=>path+'?'+new URLSearchParams(c);const state=s=>$('#status').textContent=s;
async function get(path){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),14000);try{const r=await fetch(path,{cache:'no-store',signal:controller.signal}),d=await r.json();if(!r.ok||d.ok===false)throw Error(d.error||`HTTP ${r.status}`);return d}finally{clearTimeout(timer)}}
function isComplete(f){if(!f||!f.t||!f.odds)return false;const keys=Object.keys(f.odds).filter(k=>num(f.odds[k])>0);return keys.length>=6&&types.every(p=>keys.every(k=>num(f.shares?.[p]?.[k])>0)&&num(f.pools?.[p])>0)}
function oddsOrder(f){return Object.keys(f?.odds||{}).filter(k=>num(f.odds[k])>0).sort((a,b)=>num(f.odds[a])-num(f.odds[b])||+a-+b)}
function previous(f,mins){return frames.filter(x=>x.t<f.t&&x.t>=f.t-(mins+1)*60000&&x.t<=f.t-45000).sort((a,b)=>Math.abs((f.t-a.t)/60000-mins)-Math.abs((f.t-b.t)/60000-mins))[0]||null}
function pctRanks(map,keys){const sorted=keys.slice().sort((a,b)=>num(map[a])-num(map[b]));return Object.fromEntries(sorted.map((k,i)=>[k,sorted.length===1?50:100*i/(sorted.length-1)]))}
function indicators(f){const keys=oddsOrder(f),w=f.shares?.WIN||{},prev=previous(f,2),rawSupport={},rawCross={},rawMotion={},old={};const expTotal=keys.reduce((s,k)=>s+Math.pow(num(w[k]),.75),0);
 for(const k of keys){const poolShare=p=>num(f.shares?.[p]?.[k]);rawSupport[k]=.25*poolShare('WIN')+.20*poolShare('PLA')+.27*poolShare('QIN')+.28*poolShare('QPL');const expected=expTotal?Math.pow(num(w[k]),.75)/expTotal:0;rawCross[k]=[['PLA',.25],['QIN',.35],['QPL',.4]].reduce((s,[p,weight])=>s+weight*Math.log(clamp(poolShare(p)/Math.max(expected,.000001),.2,5)),0);let numerator=0,denominator=0;if(prev){for(const p of types){const a=num(f.pools[p]),b=num(prev.pools[p]),diff=a-b,now=num(f.shares?.[p]?.[k]),before=num(prev.shares?.[p]?.[k]);if(diff>0&&now>0&&before>0){const incr=a*now-b*before;numerator+=incr-diff*before;denominator+=diff}}}rawMotion[k]=denominator>0?clamp(numerator/denominator,-1,1):0;
 const ratio=[['PLA',.2],['QIN',.36],['QPL',.44]].reduce((s,[p,weight])=>s+weight*clamp(Math.log(Math.max(poolShare(p),1e-8)/Math.max(expected,1e-8)),-1.4,1.4),0);const oldDelta=prev?clamp((poolShare('QIN')+poolShare('QPL')-num(prev.shares?.QIN?.[k])-num(prev.shares?.QPL?.[k]))*3,-.22,.22):0;old[k]=Math.round(clamp(67+31*ratio+44*oldDelta,10,120));}
 const support=pctRanks(rawSupport,keys),cross=pctRanks(rawCross,keys),motion=pctRanks(rawMotion,keys);return Object.fromEntries(keys.map(k=>{const balance=Math.round(.35*support[k]+.45*cross[k]+.20*motion[k]),momentum=Math.round(.15*support[k]+.30*cross[k]+.55*motion[k]);return[k,{support:rawSupport[k],cross:rawCross[k],motion:rawMotion[k],balance,momentum,old:old[k],score:model==='old'?old[k]:model==='momentum'?momentum:balance,hasMotion:!!prev,win:num(f.odds[k]),name:f.runners?.[k]||''}]}))}
function raceMeta(){const c=ctx(),m=(racing?.raceMeetings||[]).find(x=>x.date===c.date&&x.venueCode===c.venueCode)||racing?.raceMeetings?.[0];return(m?.races||[]).find(x=>+x.no===c.raceNo)||null}
function officialMap(){return Object.fromEntries((official?.results||[]).map(x=>[String(+x.horseNo),x]))}
function horseMeta(f,k){const r=(raceMeta()?.runners||[]).find(x=>String(+x.no)===k),o=officialMap()[k];return{name:r?.name_ch||r?.name_en||o?.horse||f.runners?.[k]||'—',trainer:r?.trainer?.name_ch||r?.trainer?.name_en||o?.trainer||'—',jockey:r?.jockey?.name_ch||r?.jockey?.name_en||o?.jockey||'—',draw:r?.barrierDrawNumber||o?.draw||'—',finish:o?.finish??null}}
function plaOdds(){const out={};for(const p of racing?.odds||[]){if(p.oddsType!=='PLA')continue;for(const n of p.oddsNodes||[]){const m=String(n.combString||'').match(/^\s*0*(\d{1,2})\s*$/),v=parseFloat(String(n.oddsValue||'').replace(/,/g,''));if(m&&v>0)out[String(+m[1])]=v}}return out}
function missing(){return'<td class="missing" title="現有資料未提供可核實數值">—</td>'}
const headers=[['finish','名次'],['horse','馬號'],['name','馬名'],['trainer','練馬師'],['jockey','騎師'],['draw','檔位'],['start','獨贏前'],['win','獨贏'],['score','研究指標','非原站熱錢指標'],['support','綜合支持%','四池估算'],['cross','跨池偏離','模型值'],['motion','短線異動','有對照快照先計'],['place','位置'],['q','連贏支持%','配對賠率推算份額'],['qp','位置Q支持%','配對賠率推算份額'],['wshare','獨贏支持%'],['pshare','位置支持%'],['up','孖寶上'],['down','孖寶下'],['ticket','逐注金額']];
function renderTable(f,values){const keys=oddsOrder(f),oldest=frames[0],om=officialMap(),place=plaOdds(),rows=keys.map(k=>({k,v:values[k],m:horseMeta(f,k)}));rows.sort((a,b)=>{if(sort==='horse')return +a.k-+b.k;if(sort==='win')return a.v.win-b.v.win||+a.k-+b.k;if(sort==='q')return num(f.shares.QIN[b.k])-num(f.shares.QIN[a.k]);if(sort==='qp')return num(f.shares.QPL[b.k])-num(f.shares.QPL[a.k]);if(sort==='finish')return num(a.m.finish||999)-num(b.m.finish||999)||+a.k-+b.k;return b.v.score-a.v.score||a.v.win-b.v.win});
$('#thead').innerHTML='<tr>'+headers.map(([key,label,hint])=>'<th data-sort="'+key+'" title="'+esc(hint||'按此欄排序')+'" class="'+(sort===key?'sorted':'')+'">'+esc(label)+(hint?'<small>估算／來源說明</small>':'')+'</th>').join('')+'</tr>';
const topScore=Math.max(...rows.map(r=>r.v.score));$('#tbody').innerHTML=rows.map((r,i)=>{const {k,v,m}=r,extra=100*num(f.shares?.QIN?.[k]),qpe=100*num(f.shares?.QPL?.[k]),p=place[k];const scoreClass=v.score===topScore?'best':'est';return'<tr><td>'+esc(m.finish??'—')+'</td><td><b>'+esc(k)+'</b></td><td class="horse">'+esc(m.name)+'</td><td>'+esc(m.trainer)+'</td><td>'+esc(m.jockey)+'</td><td>'+esc(m.draw)+'</td><td>'+esc(oldest?.odds?.[k]?fmt(oldest.odds[k]):'—')+'</td><td>'+fmt(v.win)+'</td><td class="'+scoreClass+'" title="'+esc($('#model').selectedOptions[0].textContent)+'">'+v.score+'</td><td class="est">'+pct(v.support)+'</td><td class="est">'+(v.cross>=0?'+':'')+v.cross.toFixed(2)+'</td><td class="est">'+(v.hasMotion?(v.motion>=0?'+':'')+v.motion.toFixed(2):'—')+'</td><td>'+esc(p?fmt(p):'—')+'</td><td class="est">'+extra.toFixed(1)+'</td><td class="est">'+qpe.toFixed(1)+'</td><td>'+pct(f.shares.WIN[k])+'</td><td>'+pct(f.shares.PLA[k])+'</td>'+missing()+missing()+missing()+'</tr>'}).join('');$('#tableNote').textContent='總表 '+rows.length+' 匹｜'+(official?.results?.length?'名次來自官方賽果':'未讀官方賽果，名次留空')+'｜「獨贏前」＝最早一筆已保存快照，未必係隔夜｜位置賠率只在當前 API 可讀時顯示，唔係歷史值｜Q／QP 是馬匹邊際支持估算，不是單馬 Q 賠率。孖寶／逐注金額資料未提供。';return rows}
function bar(f,values){const rows=oddsOrder(f).sort((a,b)=>values[b].score-values[a].score||num(f.odds[a])-num(f.odds[b])),max=Math.max(1,...rows.map(k=>values[k].score)),a=frames[0];$('#barTitle').textContent='R'+ctx().raceNo+' 即時熱錢分佈（'+$('#model').selectedOptions[0].textContent+'）';$('#plot').innerHTML=rows.map(k=>{const h=Math.max(4,Math.round(values[k].score/max*210));return'<div class="col" title="'+esc(values[k].name)+'｜#'+esc(k)+'｜研究指標 '+values[k].score+'｜非勝率"><div class="bar" style="--h:'+h+'px"><b>'+values[k].score+'</b></div></div>'}).join('');$('#under').innerHTML=rows.map(k=>'<span><strong>'+esc(k)+'</strong>'+fmt(f.odds[k])+'</span>').join('');$('#time').textContent='T'+(f.mtp>=0?'-':'+')+Math.abs(num(f.mtp)).toFixed(1)+' · '+time(f.t);$('#barNote').textContent='柱高係 '+$('#model').selectedOptions[0].textContent+' 自訂研究指標，按指標由高至低；下方為馬號／當刻 WIN。資料來自每約一分鐘保存嘅四池快照，與第三方熱錢演算法及逐注金額不可直接比較。';}
function spectrum(f){const keys=oddsOrder(f),prior=frames[0],minutes=[-1,0,...Array.from({length:16},(_,i)=>i+1)];const seen=frames.filter(x=>x.t<=f.t);const nearest=m=>{const a=seen.filter(x=>Math.abs(num(x.mtp)-m)<=.52).sort((x,y)=>Math.abs(x.mtp-m)-Math.abs(y.mtp-m));return a[0]||null};const shade=n=>n>30?'o':n>=20?'p':n>=10?'g':'';$('#spec').innerHTML='<thead><tr><th>馬號</th><th>獨前</th><th>獨贏</th>'+minutes.map(m=>'<th>'+m+'</th>').join('')+'</tr></thead><tbody>'+keys.map(k=>'<tr><td>'+esc(k)+'</td><td>'+esc(prior?.odds?.[k]?fmt(prior.odds[k]):'—')+'</td><td>'+fmt(f.odds[k])+'</td>'+minutes.map(m=>{const s=nearest(m);return'<td title="'+(s?'T-'+s.mtp.toFixed(1)+'；W/Q/QP 估算份額':'該分鐘未有快照')+'">'+(s?['WIN','QIN','QPL'].map(p=>'<i class="stripe '+shade(100*num(s.shares?.[p]?.[k]))+'"></i>').join(''):'')+'</td>'}).join('')+'</tr>').join('')+'</tbody>';}
function flows(f){const seen=frames.filter(x=>x.t<=f.t),out=[];for(let i=1;i<seen.length;i++){const a=seen[i-1],b=seen[i];if(b.t-a.t>180000||b.t<=a.t)continue;for(const p of types){const before=num(a.pools?.[p]),after=num(b.pools?.[p]);if(after>before&&before>0)out.push({t:b.t,p,before,after,d:after-before})}}out.sort((a,b)=>b.t-a.t||b.d-a.d);$('#flows').innerHTML=out.length?out.slice(0,100).map(x=>'<tr><td>'+time(x.t)+'</td><td>'+poolNames[x.p]+'</td><td>'+money(x.before)+'</td><td>'+money(x.after)+'</td><td>+'+money(x.d)+'</td></tr>').join(''):'<tr><td class="empty" colspan="5">呢個時間之前冇可比較嘅完整快照</td></tr>';}
function compare(values){const keys=Object.keys(values),pick=mode=>keys.slice().sort((a,b)=>values[b][mode]-values[a][mode]).slice(0,6).map(k=>'#'+k).join('、');$('#difference').innerHTML='<b>A｜跨池平衡：</b>'+pick('balance')+'<br><b>B｜短線異動：</b>'+pick('momentum')+'<br><b>C｜舊版簡化：</b>'+pick('old')+'<br><span class="hint">A = 綜合支持排名 35%＋跨池偏離排名 45%＋短線動量排名 20%；B = 15%＋30%＋55%。排名只在同場相對比較；舊版 C 保留作比較。冇兩筆合資格快照時短線動量為缺失，唔會宣稱有真實流入。</span>';}
function draw(){const f=frames[at];$('#seek').max=Math.max(0,frames.length-1);$('#seek').value=at;if(!f){$('#tbody').innerHTML='<tr><td colspan="20" class="empty">呢場暫時冇完整可用嘅四池快照，唔會造數據。</td></tr>';$('#plot').innerHTML='';$('#under').innerHTML='';$('#spec').innerHTML='';$('#flows').innerHTML='';$('#pools').innerHTML='';$('#time').textContent='—';$('#difference').textContent='需要完整快照先可以比較。';return}const val=indicators(f),rs=renderTable(f,val);bar(f,val);spectrum(f);flows(f);compare(val);$('#pools').innerHTML=types.map(p=>'<span>'+poolNames[p]+' <strong>'+money(f.pools?.[p])+'</strong></span>').join('')+'<span>可讀四池合計 <strong>'+money(types.reduce((a,p)=>a+num(f.pools?.[p]),0))+'</strong></span><span>完整快照 <strong>'+frames.length+'</strong></span>';}
async function load(){const c=ctx(),id=++reqId;frames=[];at=0;racing=null;official=null;draw();state('讀取已保存四池快照及馬匹詳細資料…');history.replaceState(null,'','/market-lab.html?'+new URLSearchParams({date:c.date,venue:c.venueCode,race:c.raceNo}));const [cloud,horse]=await Promise.allSettled([get(url('/api/qbank-cloud',c)),get(url('/api/racing',c))]);if(id!==reqId)return;racing=horse.status==='fulfilled'?horse.value:null;frames=(cloud.status==='fulfilled'?(cloud.value.frames||[]):[]).filter(isComplete).sort((a,b)=>a.t-b.t);at=Math.max(0,frames.length-1);draw();state('雲端完整快照 '+frames.length+' 筆；'+(cloud.status==='rejected'?'雲端：'+cloud.reason.message+'；':'')+(horse.status==='rejected'?'馬匹詳細資料暫時未能取得；':'')+'日期／場次及算法可自行切換。');if(c.date<today())await readResult(id,false)}
async function readResult(id=reqId,announce=true){const c=ctx();if(announce)state('正在讀取官方賽果…');try{const d=await get(url('/api/history',c));if(id!==reqId)return;official=d;draw();if(announce)state('官方賽果載入：'+(d.results||[]).length+' 匹馬；可切換總表「官方名次」排序。')}catch(e){if(id===reqId&&announce)state('官方賽果暫時不可讀：'+e.message)}}
$('#load').onclick=load;$('#result').onclick=()=>readResult();$('#date').onchange=load;$('#race').onchange=load;$('#venue').onchange=load;$('#model').onchange=e=>{model=e.target.value;draw()};$('#sort').onchange=e=>{sort=e.target.value;draw()};$('#seek').oninput=e=>{at=+e.target.value;draw()};$('#back').onclick=()=>{at=Math.max(0,at-1);draw()};$('#next').onclick=()=>{at=Math.min(frames.length-1,at+1);draw()};$('#thead').onclick=e=>{const th=e.target.closest('th[data-sort]');if(!th)return;const x=th.dataset.sort;const sel={finish:'finish',horse:'horse',win:'win',score:'signal',q:'q',qp:'qp'}[x];if(sel){sort=sel;$('#sort').value=sel;draw()}};load();
})();