const ENDPOINT='https://info.cld.hkjc.com/graphql/base/';
const HEADERS={'content-type':'application/json','accept':'application/json, text/plain, */*','accept-language':'zh-HK,zh;q=0.9,en;q=0.8','origin':'https://bet.hkjc.com','referer':'https://bet.hkjc.com/','user-agent':'Mozilla/5.0'};
const TYPES=['WIN','PLA','QIN','QPL','FCT','TRI','TCE','FF'];
const QUERY=`query lateMoney($date:String,$venueCode:String,$raceNo:Int,$oddsTypes:[OddsType]){raceMeetings(date:$date,venueCode:$venueCode){date venueCode races{no postTime runners{no status name_ch name_en winOdds}} pmPools(oddsTypes:$oddsTypes,raceNo:$raceNo){id oddsType status sellStatus investment lastUpdateTime leg{races} oddsNodes{combString oddsValue hotFavourite oddsDropValue}}}}`;
async function gql(variables){const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),9000);try{const r=await fetch(ENDPOINT,{method:'POST',headers:HEADERS,body:JSON.stringify({operationName:'lateMoney',query:QUERY,variables}),signal:ctl.signal});const t=await r.text();let j;try{j=JSON.parse(t)}catch{throw new Error('HKJC invalid JSON')}if(!r.ok||j.errors?.length)throw new Error(j.errors?.map(x=>x.message).join('; ')||`HKJC HTTP ${r.status}`);return j.data;}finally{clearTimeout(tm)}}
function nums(v){return (String(v??'').match(/\d+/g)||[]).map(Number).filter(n=>n>0)}
function val(v){v=Number(v);return Number.isFinite(v)&&v>0?v:null}
function marginal(pool){const raw={};let total=0;for(const n of pool?.oddsNodes||[]){const o=val(n.oddsValue),a=nums(n.combString);if(!o||!a.length)continue;const w=1/o,each=w/a.length;for(const h of a)raw[h]=(raw[h]||0)+each;total+=w}const out={};if(total>0)for(const k of Object.keys(raw))out[k]=raw[k]/total;return out}
function pctEx(poolShare,winShare){if(!(poolShare>0)||!(winShare>0))return null;return poolShare/winShare-1}
export default async function handler(req,res){try{const raceNo=Math.max(1,Number(req.query.raceNo||1)),date=req.query.date||null,venueCode=req.query.venueCode||null;if(!date||!venueCode)throw new Error('date and venueCode required');const data=await gql({date,venueCode,raceNo,oddsTypes:TYPES}),m=data?.raceMeetings?.[0];if(!m)throw new Error('No race meeting');const race=(m.races||[]).find(r=>Number(r.no)===raceNo);if(!race)throw new Error('Race not found');const pools=(m.pmPools||[]).filter(p=>(p.leg?.races||[]).map(Number).includes(raceNo));const byType={};for(const p of pools)byType[p.oddsType]=p;const shares={};for(const t of TYPES)shares[t]=marginal(byType[t]);const horses={};for(const r of race.runners||[]){const no=Number(r.no);if(!no||r.status==='Standby')continue;const win=shares.WIN?.[no]||0,ps={};for(const t of TYPES){const s=shares[t]?.[no]||0;ps[t]={share:s||null,excess:t==='WIN'?0:pctEx(s,win)}}horses[no]={no,name:r.name_ch||r.name_en||'',winOdds:val(r.winOdds),pools:ps};}
const meta={};for(const t of TYPES){const p=byType[t];meta[t]=p?{investment:val(p.investment),lastUpdateTime:p.lastUpdateTime||null,nodeCount:(p.oddsNodes||[]).length,status:p.status||null}:null}
res.setHeader('Cache-Control','no-store, max-age=0');res.status(200).json({ok:true,fetchedAt:new Date().toISOString(),resolved:{date,venueCode,raceNo},postTime:race.postTime||null,types:TYPES,horses,pools:meta,note:'Heuristic marginal support derived from public parimutuel odds; not ticket counts or identified bettors.'});}catch(e){res.setHeader('Cache-Control','no-store, max-age=0');res.status(502).json({ok:false,error:e?.name==='AbortError'?'HKJC request timeout':(e?.message||'late-money unavailable'),fetchedAt:new Date().toISOString()})}}
